version: '3'

services:
  vpn:
    build: .
    volumes:
      - '.:/vpn'
      - ./data/certbot/conf:/etc/letsencrypt
    command: /usr/bin/start-vpn
    privileged: true
    ports:
      - '500:500/udp'
      - '4500:4500/udp'
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"